name: release

on:
  push:
    branches:
      - main
      - get-bump-label

  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: bump_labels
        id: bump-label
        uses: SamirMarin/get-bump-label-action@get-bump-label
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: echo-test
        run: |
          echo ${{ steps.bump-label.outputs.labels }}
          echo ${{ steps.bump-label.outputs.label_value }}