name: release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: bump_labels
        id: bump-label
        uses: SamirMarin/get-bump-label-action@get-bump-label
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: echo-test
        run: echo ${{ steps.bump-label.outputs.label_value }}